config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "genres/index", to: "genres#index"
  get "directors/index", to: "directors#index"
  get "movies/index", to: "movies#index"
  resources :genres, only: [:show, :new, :create, :edit, :update]
  resources :movies, only: [:show, :new, :create, :edit, :update]
  resources :directors, only: [:show, :new, :create, :edit, :update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
    has_many :movies
    has_many :genres, through: :movies
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :movies
  end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director
  belongs_to :genre

  enum status: { unreleased: 0, released: 1}
  has_one_attached :poster
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
    def show
        @director = Director.find(params[:id])
        @movies = Movie.where(director_id: @director.id)
    end

    def index
        @directors = Director.all
    end

    def new
        @director = Director.new
    end

    def create
        @director = Director.new(director_params)

        if @director.save
            redirect_to root_path, notice: 'Director was successfully created.'
        else
            render :new
        end
    end

    def edit
        @director = Director.find(params[:id])
    end

    def update
        @director = Director.find(params[:id])

        if @director.update(director_params)
            redirect_to root_path, notice: 'Director was successfully updated.'
        else
            render :edit
        end
    end

    private

    def director_params
        params.require(:director).permit(:name, :age, :nationality, :favorite_genre)
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

    def show
        @genre = Genre.find(params[:id])
        @movies = Movie.where(genre_id: @genre.id)
    end

    def index
        @genres = Genre.all
    end
    
    def new
        @genre = Genre.new
    end

    def create
        @genre = Genre.new(genre_params)

        if @genre.save
            redirect_to root_path, notice: 'Genre was successfully created.'
        else
            render :new
        end
    end

    def edit
        @genre = Genre.find(params[:id])
    end

    def update
        @genre = Genre.find(params[:id])
        if @genre.update(genre_params)
            redirect_to root_path, notice: "Genêro atualizado com sucesso!"
        else
            render :edit
        end
    end

    private

    def genre_params
        params.require(:genre).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @genres = Genre.all
        @movies = Movie.all
        @directors = Director.all        
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def show
        @movie = Movie.find(params[:id])
        @genres = @movie.genre
        @director = @movie.director
    end

    def index
        @movies = Movie.all
    end

    def new
        @movie = Movie.new
    end

    def create
        @movie = Movie.new(movie_params)

        if @movie.save
            redirect_to root_path, notice: 'Movie was successfully created.'
        else
            render :new
        end
    end

    def edit
        @movie = Movie.find(params[:id])
    end

    def update
        @movie = Movie.find(params[:id])

        if @movie.update(movie_params)
            redirect_to root_path, notice: 'Movie was successfully updated.'
        else
            render :edit
        end
    end

    private

    def movie_params
        params.require(:movie).permit(:title, :director_id, :synopsis, :country, :duration, :year, :genre_id, :status, :poster)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/director_helper.rb
module DirectorHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/views/directors/_form.html.erb
<%= form_with(model: @director, local: true) do |form| %>
    <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div class="field">
        <%= form.label :date_of_birth %>
        <%= form.date_field :date_of_birth %>
    </div>

    <div class="field">
        <%= form.label :country %>
        <%= form.text_field :country %>
    </div>

    <div class="field">
        <%= form.label :favorite_genre%>
        <%= form.collection_select :favorite_genre_id, Genre.all, :id, :name%>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/directors/edit.html.erb
<%= render partial: 'form', locals: { director: @director } %>

app/views/directors/index.html.erb
<h1>Directors</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @directors.each do |director| %>
            <tr>
                <td><%= director.name %></td>
                <td>
                    <%= link_to 'Edit', edit_director_path(director) %>
                </td>
                <td>
                    <%= link_to 'Show', director_path(director) %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/directors/new.html.erb
<%= render partial: 'form', locals: { director: @director } %>

app/views/directors/show.html.erb
<h1><%= @director.name %></h1>

<h2>Filmes que ele dirigiu::</h2>
<% @movies.each do |movie| %>
  <p>
    <%= movie.title %>
  </p>
<% end %>

app/views/genres/_form.html.erb
<%= form_with(model: @genre) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<%= render 'form', genre: @genres %>

app/views/genres/index.html.erb
<h1>Genres</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @genres.each do |genre| %>
            <tr>
                <td><%= genre.name %></td>
                <td>
                    <%= link_to 'Edit', edit_genre_path(genre) %>
                </td>
                <td>
                    <%= link_to 'Show', genre_path(genre) %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/genres/new.html.erb
<%= render 'form', genre: @genre %>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>

<h2>Filmes com esse genêro:</h2>
<% @movies.each do |movie| %>
  <p>
    <%= movie.title %>
  </p>
<% end %>

app/views/home/index.html.erb
<head>
    <title>Welcome to Movie Catalog</title>
</head>
<body>
    <nav>
        <h1>Welcome to Movie Catalog</h1>
        <p>Obs, aqui você encontra apenas filmes bons</p>
        <div class="register-options">
            <%= link_to "Register Genre", new_genre_path %>
            <%= link_to "Register Director", new_director_path %>
            <%= link_to "Register Movie", new_movie_path %>
        </div>
    </nav>
    <div class="genre-list">
        <h2>Registered Genres:</h2>
        <% @genres.each do |genre| %>
            <p><%= genre.name %></p>
        <% end %>
    </div>
    <div class="director-list">
        <h2>Registered Directors:</h2>
        <% @directors.each do |director| %>
            <p><%= director.name %></p>
        <% end %>
    </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieCatalog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <footer>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Movies", movies_index_path %></li>
        <li><%= link_to "Directors", directors_index_path %></li>
        <li><%= link_to "Generos", genres_index_path %></li>
      </ul>
    </footer>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do | form | %>
    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div class="field">
        <%= form.label :year %>
        <%= form.number_field :year %>
    </div>
   
    <div class="field">  
        <%= form.label :synopsis %>
        <%= form.text_area :synopsis %>
    </div>

    <div class="field">
        <%= form.label :country %>
        <%= form.text_field :country %>
    </div>

    <div class="field">
        <%= form.label :duration %>
        <%= form.number_field :duration %>
    </div>

    <div class="field">
        <%= form.label :genre%>
        <%= form.collection_select :genre_id, Genre.all, :id, :name%>
    </div>

    <div class="field">
        <%= form.label :director%>
        <%= form.collection_select :director_id, Director.all, :id, :name%>
    </div>
    <div>
        <%= form.select :status, Movie.statuses.keys %>
    </div>
    <div>
        <%= form.label "Movie Poster" %>
        <%= form.file_field :poster %><br>
    </div>
    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/movies/edit.html.erb
<%= render partial: "form", locals: {movie: @movie} %>

app/views/movies/index.html.erb
<header> Movies </header>
<table>
  <thead>
    <tr>
      <th>Poster</th>
      <th>Title</th>
      <th>Release Year</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td>
          <% if movie.poster.attached? %>
            <img src="<%= url_for(movie.poster) %>" alt="Poster for <%= movie.title %>" style="width: 150px;">
          <% end %>
        </td>
        <td><%= movie.title %></td>
        <td><%= movie.year %></td>
        <td><%= movie.status %></td>
        <td><%= link_to "View Details", movie_path(movie) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/new.html.erb
<%= render partial: "form", locals: {movie: @movie} %>

app/views/movies/show.html.erb
<h1>Movie Details</h1>
<div>
    <% if @movie.poster.attached? %>
        <img src="<%= url_for(@movie.poster) %>">
    <% end %>
</div>
    <p><strong>Title:</strong> <%= @movie.title %></p>
    <p><strong>Genre:</strong> <%= @genres.name %></p>
    <p><strong>Director:</strong> <%= @director.name %></p>
    <p><strong>Synopsis:</strong> <%= @movie.synopsis %></p>
    <p><strong>Country:</strong> <%= @movie.country %></p>
    <p><strong>Duration:</strong> <%= @movie.duration %> minutes</p>
    <p><strong>Status: <%= @movie.status %></strong></p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_index_path %>